name: rxp
recipe: drupal10
config:
  webroot: web

proxy:
  appserver:
    - rxp.lndo.site
    - s1.rxp.lndo.site
    - s2.rxp.lndo.site
    - s3.rxp.lndo.site

services:
  appserver:
    type: php:8.2

  dbs1:
    type: mariadb
    creds:
      database: dbs1
      user: drupal10
      password: drupal10

  dbs2:
    type: mariadb
    creds:
      database: dbs2
      user: drupal10
      password: drupal10

  dbs3:
    type: mariadb
    creds:
      database: dbs3
      user: drupal10
      password: drupal10

tooling:
  fresh_install:
    service: appserver
    cmd: /app/scripts/fresh_install.sh
    options:
      site:
        default: none

  phpcs:
    service: appserver
    cmd: /app/vendor/bin/phpcs
