name: rxp
recipe: drupal10
config:
  webroot: web

proxy:
  appserver:
    - rxp.lndo.site
    - s1.rxp.lndo.site
    - s2.rxp.lndo.site
    - s3.rxp.lndo.site

services:
  appserver:
    type: php:8.2
