adding:
  dependencies:
    config:
      - field.field.paragraph.body_copy.field_title
  content:
    field_title:
      type: string_textfield
      weight: 0
      region: content
      settings:
        size: 60
        placeholder: ''
      third_party_settings: {  }
removing: {  }
