adding:
  dependencies:
    config:
      - field.field.paragraph.body_copy.field_title
  content:
    field_title:
      type: string
      label: hidden
      settings:
        link_to_entity: false
      third_party_settings: {  }
      weight: 0
      region: content
removing: {  }
